In [1]:
import requests
import pandas as pd
import datetime
import time
import pyodbc as odbc

In [2]:
api_key = "9c31defb68c5ac281ef53ad13569fa29d295e408"

In [3]:
endpoint = f"https://api.jcdecaux.com/vls/v1/stations?contract=dublin&apiKey={api_key}"

In [4]:
resp = requests.get(endpoint)
resp

In [5]:
resp.content

b'[{"number":42,"contract_name":"dublin","name":"SMITHFIELD NORTH","address":"Smithfield North","position":{"lat":53.349562,"lng":-6.278198},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":26,"available_bikes":4,"status":"OPEN","last_update":1712657065000},{"number":30,"contract_name":"dublin","name":"PARNELL SQUARE NORTH","address":"Parnell Square North","position":{"lat":53.3537415547453,"lng":-6.26530144781526},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":13,"available_bikes":6,"status":"OPEN","last_update":1712657057000},{"number":54,"contract_name":"dublin","name":"CLONMEL STREET","address":"Clonmel Street","position":{"lat":53.336021,"lng":-6.26298},"banking":false,"bonus":false,"bike_stands":33,"available_bike_stands":27,"available_bikes":6,"status":"OPEN","last_update":1712657047000},{"number":108,"contract_name":"dublin","name":"AVONDALE ROAD","address":"Avondale Road","position":{"lat":53.359405,"lng":-6.276142},"banking":false,"bonus":false,"bike_stands":35,"available_bike_stands":25,"available_bikes":10,"status":"OPEN","last_update":1712656943000},{"number":20,"contract_name":"dublin","name":"JAMES STREET EAST","address":"James Street East","position":{"lat":53.336597,"lng":-6.248109},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":1,"available_bikes":29,"status":"OPEN","last_update":1712657041000},{"number":56,"contract_name":"dublin","name":"MOUNT STREET LOWER","address":"Mount Street Lower","position":{"lat":53.33796,"lng":-6.24153},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":18,"available_bikes":22,"status":"OPEN","last_update":1712657079000},{"number":6,"contract_name":"dublin","name":"CHRISTCHURCH PLACE","address":"Christchurch Place","position":{"lat":53.343368,"lng":-6.27012},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":18,"available_bikes":2,"status":"OPEN","last_update":1712656787000},{"number":18,"contract_name":"dublin","name":"GRANTHAM STREET","address":"Grantham Street","position":{"lat":53.334123,"lng":-6.265436},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":27,"available_bikes":3,"status":"OPEN","last_update":1712656954000},{"number":32,"contract_name":"dublin","name":"PEARSE STREET","address":"Pearse Street","position":{"lat":53.344304,"lng":-6.250427},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":18,"available_bikes":12,"status":"OPEN","last_update":1712656972000},{"number":52,"contract_name":"dublin","name":"YORK STREET EAST","address":"York Street East","position":{"lat":53.338755,"lng":-6.262003},"banking":false,"bonus":false,"bike_stands":32,"available_bike_stands":28,"available_bikes":4,"status":"OPEN","last_update":1712656851000},{"number":48,"contract_name":"dublin","name":"EXCISE WALK","address":"Excise Walk","position":{"lat":53.347777,"lng":-6.244239},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":29,"available_bikes":11,"status":"OPEN","last_update":1712656937000},{"number":13,"contract_name":"dublin","name":"FITZWILLIAM SQUARE WEST","address":"Fitzwilliam Square West","position":{"lat":53.336074,"lng":-6.252825},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":14,"available_bikes":16,"status":"OPEN","last_update":1712656908000},{"number":43,"contract_name":"dublin","name":"PORTOBELLO ROAD","address":"Portobello Road","position":{"lat":53.330091,"lng":-6.268044},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":21,"available_bikes":9,"status":"OPEN","last_update":1712657054000},{"number":31,"contract_name":"dublin","name":"PARNELL STREET","address":"Parnell Street","position":{"lat":53.350929,"lng":-6.265125},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":6,"available_bikes":14,"status":"OPEN","last_update":1712657165000},{"number":98,"contract_name":"dublin","name":"FREDERICK STREET SOUTH","address":"Frederick Street South","position":{"lat":53.341515,"lng":-6.256853},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":33,"available_bikes":7,"status":"OPEN","last_update":1712656922000},{"number":14,"contract_name":"dublin","name":"FOWNES STREET UPPER","address":"Fownes Street Upper","position":{"lat":53.344603,"lng":-6.263371},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":15,"available_bikes":15,"status":"OPEN","last_update":1712656979000},{"number":1,"contract_name":"dublin","name":"CLARENDON ROW","address":"Clarendon Row","position":{"lat":53.340927,"lng":-6.262501},"banking":false,"bonus":false,"bike_stands":31,"available_bike_stands":10,"available_bikes":21,"status":"OPEN","last_update":1712656799000},{"number":23,"contract_name":"dublin","name":"CUSTOM HOUSE","address":"Custom House","position":{"lat":53.348279,"lng":-6.254662},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":25,"available_bikes":5,"status":"OPEN","last_update":1712656951000},{"number":106,"contract_name":"dublin","name":"RATHDOWN ROAD","address":"Rathdown Road","position":{"lat":53.35893,"lng":-6.280337},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":20,"available_bikes":20,"status":"OPEN","last_update":1712656799000},{"number":112,"contract_name":"dublin","name":"NORTH CIRCULAR ROAD (O\'CONNELL\'S)","address":"North Circular Road (O\'Connell\'s)","position":{"lat":53.357841,"lng":-6.251557},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":17,"available_bikes":13,"status":"OPEN","last_update":1712656891000},{"number":68,"contract_name":"dublin","name":"HANOVER QUAY","address":"Hanover Quay","position":{"lat":53.344115,"lng":-6.237153},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":10,"available_bikes":30,"status":"OPEN","last_update":1712656955000},{"number":74,"contract_name":"dublin","name":"OLIVER BOND STREET","address":"Oliver Bond Street","position":{"lat":53.343893,"lng":-6.280531},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":29,"available_bikes":1,"status":"OPEN","last_update":1712656983000},{"number":87,"contract_name":"dublin","name":"COLLINS BARRACKS MUSEUM","address":"Collins Barracks Museum","position":{"lat":53.347477,"lng":-6.28525},"banking":false,"bonus":false,"bike_stands":38,"available_bike_stands":38,"available_bikes":0,"status":"OPEN","last_update":1712656869000},{"number":84,"contract_name":"dublin","name":"BROOKFIELD ROAD","address":"Brookfield Road","position":{"lat":53.339005,"lng":-6.300217},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":21,"available_bikes":9,"status":"OPEN","last_update":1712656993000},{"number":90,"contract_name":"dublin","name":"BENSON STREET","address":"Benson Street","position":{"lat":53.344153,"lng":-6.233451},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":8,"available_bikes":29,"status":"OPEN","last_update":1712657079000},{"number":11,"contract_name":"dublin","name":"EARLSFORT TERRACE","address":"Earlsfort Terrace","position":{"lat":53.334295,"lng":-6.258503},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":10,"available_bikes":20,"status":"OPEN","last_update":1712657030000},{"number":17,"contract_name":"dublin","name":"GOLDEN LANE","address":"Golden Lane","position":{"lat":53.340803,"lng":-6.267732},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":17,"available_bikes":3,"status":"OPEN","last_update":1712657045000},{"number":45,"contract_name":"dublin","name":"DEVERELL PLACE","address":"Deverell Place","position":{"lat":53.351464,"lng":-6.255265},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":30,"available_bikes":0,"status":"OPEN","last_update":1712657085000},{"number":114,"contract_name":"dublin","name":"WILTON TERRACE (PARK)","address":"Wilton Terrace (Park)","position":{"lat":53.333653,"lng":-6.248345},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":12,"available_bikes":28,"status":"OPEN","last_update":1712657033000},{"number":72,"contract_name":"dublin","name":"JOHN STREET WEST","address":"John Street West","position":{"lat":53.343105,"lng":-6.277167},"banking":false,"bonus":false,"bike_stands":31,"available_bike_stands":30,"available_bikes":1,"status":"OPEN","last_update":1712656873000},{"number":63,"contract_name":"dublin","name":"FENIAN STREET","address":"Fenian Street","position":{"lat":53.341428,"lng":-6.24672},"banking":false,"bonus":false,"bike_stands":35,"available_bike_stands":27,"available_bikes":8,"status":"OPEN","last_update":1712656945000},{"number":113,"contract_name":"dublin","name":"MERRION SQUARE SOUTH","address":"Merrion Square South","position":{"lat":53.338614,"lng":-6.248606},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":24,"available_bikes":16,"status":"OPEN","last_update":1712657202000},{"number":91,"contract_name":"dublin","name":"SOUTH DOCK ROAD","address":"South Dock Road","position":{"lat":53.341833,"lng":-6.231291},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":9,"available_bikes":21,"status":"OPEN","last_update":1712656839000},{"number":99,"contract_name":"dublin","name":"CITY QUAY","address":"City Quay","position":{"lat":53.346637,"lng":-6.246154},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":25,"available_bikes":5,"status":"OPEN","last_update":1712656986000},{"number":9,"contract_name":"dublin","name":"EXCHEQUER STREET","address":"Exchequer Street","position":{"lat":53.343034,"lng":-6.263578},"banking":false,"bonus":false,"bike_stands":24,"available_bike_stands":8,"available_bikes":16,"status":"OPEN","last_update":1712657004000},{"number":67,"contract_name":"dublin","name":"THE POINT","address":"The Point","position":{"lat":53.346867,"lng":-6.230852},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":36,"available_bikes":4,"status":"OPEN","last_update":1712657206000},{"number":116,"contract_name":"dublin","name":"BROADSTONE","address":"Broadstone","position":{"lat":53.3547,"lng":-6.272314},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":30,"available_bikes":0,"status":"OPEN","last_update":1712656781000},{"number":55,"contract_name":"dublin","name":"HATCH STREET","address":"Hatch Street","position":{"lat":53.33403,"lng":-6.260714},"banking":false,"bonus":false,"bike_stands":36,"available_bike_stands":7,"available_bikes":29,"status":"OPEN","last_update":1712657026000},{"number":62,"contract_name":"dublin","name":"LIME STREET","address":"Lime Street","position":{"lat":53.346026,"lng":-6.243576},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":20,"available_bikes":20,"status":"OPEN","last_update":1712656916000},{"number":5,"contract_name":"dublin","name":"CHARLEMONT PLACE","address":"Charlemont Street","position":{"lat":53.330662,"lng":-6.260177},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":29,"available_bikes":11,"status":"OPEN","last_update":1712657140000},{"number":97,"contract_name":"dublin","name":"KILMAINHAM GAOL","address":"Kilmainham Gaol","position":{"lat":53.342113,"lng":-6.310015},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":36,"available_bikes":4,"status":"OPEN","last_update":1712656893000},{"number":61,"contract_name":"dublin","name":"HARDWICKE PLACE","address":"Hardwicke Place","position":{"lat":53.357043,"lng":-6.263232},"banking":false,"bonus":false,"bike_stands":25,"available_bike_stands":6,"available_bikes":19,"status":"OPEN","last_update":1712656809000},{"number":77,"contract_name":"dublin","name":"WOLFE TONE STREET","address":"Wolfe Tone Street","position":{"lat":53.348875,"lng":-6.267459},"banking":false,"bonus":false,"bike_stands":29,"available_bike_stands":23,"available_bikes":6,"status":"OPEN","last_update":1712656885000},{"number":73,"contract_name":"dublin","name":"FRANCIS STREET","address":"Francis Street","position":{"lat":53.342081,"lng":-6.275233},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":30,"available_bikes":0,"status":"OPEN","last_update":1712656942000},{"number":4,"contract_name":"dublin","name":"GREEK STREET","address":"Greek Street","position":{"lat":53.346874,"lng":-6.272976},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":3,"available_bikes":17,"status":"OPEN","last_update":1712656965000},{"number":49,"contract_name":"dublin","name":"GUILD STREET","address":"Guild Street","position":{"lat":53.347932,"lng":-6.240928},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":39,"available_bikes":1,"status":"OPEN","last_update":1712656799000},{"number":19,"contract_name":"dublin","name":"HERBERT PLACE","address":"Herbert Place","position":{"lat":53.334432,"lng":-6.245575},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":5,"available_bikes":24,"status":"OPEN","last_update":1712657202000},{"number":7,"contract_name":"dublin","name":"HIGH STREET","address":"High Street","position":{"lat":53.343565,"lng":-6.275071},"banking":false,"bonus":false,"bike_stands":29,"available_bike_stands":28,"available_bikes":1,"status":"OPEN","last_update":1712656937000},{"number":60,"contract_name":"dublin","name":"NORTH CIRCULAR ROAD","address":"North Circular Road","position":{"lat":53.359624,"lng":-6.260348},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":21,"available_bikes":9,"status":"OPEN","last_update":1712657064000},{"number":102,"contract_name":"dublin","name":"WESTERN WAY","address":"Western Way","position":{"lat":53.354929,"lng":-6.269425},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":26,"available_bikes":14,"status":"OPEN","last_update":1712656853000},{"number":38,"contract_name":"dublin","name":"TALBOT STREET","address":"Talbot Street","position":{"lat":53.350974,"lng":-6.25294},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":17,"available_bikes":23,"status":"OPEN","last_update":1712657055000},{"number":53,"contract_name":"dublin","name":"NEWMAN HOUSE","address":"Newman House","position":{"lat":53.337132,"lng":-6.26059},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":20,"available_bikes":20,"status":"OPEN","last_update":1712656899000},{"number":58,"contract_name":"dublin","name":"SIR PATRICK DUN\'S","address":"Sir Patrick\'s Dun","position":{"lat":53.339218,"lng":-6.240642},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":0,"available_bikes":40,"status":"OPEN","last_update":1712656984000},{"number":66,"contract_name":"dublin","name":"NEW CENTRAL BANK","address":"New Central Bank","position":{"lat":53.347122,"lng":-6.234749},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":18,"available_bikes":22,"status":"OPEN","last_update":1712657131000},{"number":104,"contract_name":"dublin","name":"GRANGEGORMAN LOWER (CENTRAL)","address":"Grangegorman Lower (Central)","position":{"lat":53.355173,"lng":-6.278424},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":28,"available_bikes":12,"status":"OPEN","last_update":1712657016000},{"number":101,"contract_name":"dublin","name":"KING STREET NORTH","address":"King Street North","position":{"lat":53.350291,"lng":-6.273507},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":25,"available_bikes":5,"status":"OPEN","last_update":1712656975000},{"number":115,"contract_name":"dublin","name":"KILLARNEY STREET","address":"Killarney Street","position":{"lat":53.354845,"lng":-6.247579},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":30,"available_bikes":0,"status":"OPEN","last_update":1712657063000},{"number":47,"contract_name":"dublin","name":"HERBERT STREET","address":"Herbert Street","position":{"lat":53.335742,"lng":-6.24551},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":25,"available_bikes":15,"status":"OPEN","last_update":1712656846000},{"number":117,"contract_name":"dublin","name":"HANOVER QUAY EAST","address":"Hanover Quay East","position":{"lat":53.343653,"lng":-6.231755},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":6,"available_bikes":34,"status":"OPEN","last_update":1712656855000},{"number":8,"contract_name":"dublin","name":"CUSTOM HOUSE QUAY","address":"Custom House Quay","position":{"lat":53.347884,"lng":-6.248048},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":26,"available_bikes":4,"status":"OPEN","last_update":1712657011000},{"number":27,"contract_name":"dublin","name":"MOLESWORTH STREET","address":"Molesworth Street","position":{"lat":53.341288,"lng":-6.258117},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":6,"available_bikes":14,"status":"OPEN","last_update":1712657200000},{"number":16,"contract_name":"dublin","name":"GEORGES QUAY","address":"Georges Quay","position":{"lat":53.347508,"lng":-6.252192},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":20,"available_bikes":0,"status":"OPEN","last_update":1712657018000},{"number":96,"contract_name":"dublin","name":"KILMAINHAM LANE","address":"Kilmainham Lane","position":{"lat":53.341805,"lng":-6.305085},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":14,"available_bikes":16,"status":"OPEN","last_update":1712656788000},{"number":82,"contract_name":"dublin","name":"MOUNT BROWN","address":"Mount Brown","position":{"lat":53.341645,"lng":-6.29719},"banking":false,"bonus":false,"bike_stands":22,"available_bike_stands":22,"available_bikes":0,"status":"OPEN","last_update":1712656833000},{"number":76,"contract_name":"dublin","name":"MARKET STREET SOUTH","address":"Market Street South","position":{"lat":53.342296,"lng":-6.287661},"banking":false,"bonus":false,"bike_stands":38,"available_bike_stands":35,"available_bikes":3,"status":"OPEN","last_update":1712656803000},{"number":71,"contract_name":"dublin","name":"KEVIN STREET","address":"Kevin Street","position":{"lat":53.337757,"lng":-6.267699},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":33,"available_bikes":6,"status":"OPEN","last_update":1712656831000},{"number":79,"contract_name":"dublin","name":"ECCLES STREET EAST","address":"Eccles Street East","position":{"lat":53.358115,"lng":-6.265601},"banking":false,"bonus":false,"bike_stands":27,"available_bike_stands":12,"available_bikes":15,"status":"OPEN","last_update":1712657093000},{"number":69,"contract_name":"dublin","name":"GRAND CANAL DOCK","address":"Grand Canal Dock","position":{"lat":53.342638,"lng":-6.238695},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":8,"available_bikes":30,"status":"OPEN","last_update":1712657146000},{"number":25,"contract_name":"dublin","name":"MERRION SQUARE EAST","address":"Merrion Square East","position":{"lat":53.339434,"lng":-6.246548},"banking":false,"bonus":false,"bike_stands":30,"available_bike_stands":4,"available_bikes":26,"status":"OPEN","last_update":1712657082000},{"number":51,"contract_name":"dublin","name":"YORK STREET WEST","address":"York Street West","position":{"lat":53.339334,"lng":-6.264699},"banking":false,"bonus":false,"bike_stands":40,"available_bike_stands":31,"available_bikes":9,"status":"OPEN","last_update":1712656790000},{"number":37,"contract_name":"dublin","name":"ST. STEPHEN\'S GREEN SOUTH","address":"St. Stephen\'s Green South","position":{"lat":53.337494,"lng":-6.26199},"banking":true,"bonus":false,"bike_stands":30,"available_bike_stands":16,"available_bikes":14,"status":"OPEN","last_update":1712656836000},{"number":59,"contract_name":"dublin","name":"DENMARK STREET GREAT","address":"Denmark Street Great","position":{"lat":53.35561,"lng":-6.261397},"banking":false,"bonus":false,"bike_stands":20,"available_bike_stands":12,"available_bikes":8,"status":"OPEN","last_update":1712656980000},{"number":95,"contract_name":"dublin","name":"ROYAL HOSPIT

In [6]:
data = resp.json()

In [7]:
df = pd.DataFrame(data)
df

,number,contract_name,name,address,position,banking,bonus,bike_stands,available_bike_stands,available_bikes,status,last_update
0,42,dublin,SMITHFIELD NORTH,Smithfield North,"{'lat': 53.349562, 'lng': -6.278198}",False,False,30,26,4,OPEN,1712657065000
1,30,dublin,PARNELL SQUARE NORTH,Parnell Square North,"{'lat': 53.3537415547453, 'lng': -6.2653014478...",False,False,20,13,6,OPEN,1712657057000
2,54,dublin,CLONMEL STREET,Clonmel Street,"{'lat': 53.336021, 'lng': -6.26298}",False,False,33,27,6,OPEN,1712657047000
3,108,dublin,AVONDALE ROAD,Avondale Road,"{'lat': 53.359405, 'lng': -6.276142}",False,False,35,25,10,OPEN,1712656943000
4,20,dublin,JAMES STREET EAST,James Street East,"{'lat': 53.336597, 'lng': -6.248109}",False,False,30,1,29,OPEN,1712657041000
...,...,...,...,...,...,...,...,...,...,...,...,...
109,39,dublin,WILTON TERRACE,Wilton Terrace,"{'lat': 53.332383, 'lng': -6.252717}",False,False,20,20,0,OPEN,1712657029000
110,83,dublin,EMMET ROAD,Emmet Road,"{'lat': 53.340714, 'lng': -6.308191}",False,False,40,28,12,OPEN,1712656943000
111,92,dublin,HEUSTON BRIDGE (NORTH),Heuston Bridge (North),"{'lat': 53.347802, 'lng': -6.292432}",False,False,40,40,0,OPEN,1712657099000
112,21,dublin,LEINSTER STREET SOUTH,Leinster Street South,"{'lat': 53.34218, 'lng': -6.254485}",False,False,30,1,29,OPEN,1712656811000
113,88,dublin,BLACKHALL PLACE,Blackhall Place,"{'lat': 53.3488, 'lng': -6.281637}",False,False,30,20,10,OPEN,1712656939000

In [8]:
def convert_timestamp(t):
    timestamp_seconds = t/1000
    return datetime.datetime.fromtimestamp(timestamp_seconds).strftime('%Y-%m-%d %H:%M:%S')

In [9]:
df['last_update'] = df['last_update'].apply(convert_timestamp)

In [10]:
df

,number,contract_name,name,address,position,banking,bonus,bike_stands,available_bike_stands,available_bikes,status,last_update
0,42,dublin,SMITHFIELD NORTH,Smithfield North,"{'lat': 53.349562, 'lng': -6.278198}",False,False,30,26,4,OPEN,2024-04-09 11:04:25
1,30,dublin,PARNELL SQUARE NORTH,Parnell Square North,"{'lat': 53.3537415547453, 'lng': -6.2653014478...",False,False,20,13,6,OPEN,2024-04-09 11:04:17
2,54,dublin,CLONMEL STREET,Clonmel Street,"{'lat': 53.336021, 'lng': -6.26298}",False,False,33,27,6,OPEN,2024-04-09 11:04:07
3,108,dublin,AVONDALE ROAD,Avondale Road,"{'lat': 53.359405, 'lng': -6.276142}",False,False,35,25,10,OPEN,2024-04-09 11:02:23
4,20,dublin,JAMES STREET EAST,James Street East,"{'lat': 53.336597, 'lng': -6.248109}",False,False,30,1,29,OPEN,2024-04-09 11:04:01
...,...,...,...,...,...,...,...,...,...,...,...,...
109,39,dublin,WILTON TERRACE,Wilton Terrace,"{'lat': 53.332383, 'lng': -6.252717}",False,False,20,20,0,OPEN,2024-04-09 11:03:49
110,83,dublin,EMMET ROAD,Emmet Road,"{'lat': 53.340714, 'lng': -6.308191}",False,False,40,28,12,OPEN,2024-04-09 11:02:23
111,92,dublin,HEUSTON BRIDGE (NORTH),Heuston Bridge (North),"{'lat': 53.347802, 'lng': -6.292432}",False,False,40,40,0,OPEN,2024-04-09 11:04:59
112,21,dublin,LEINSTER STREET SOUTH,Leinster Street South,"{'lat': 53.34218, 'lng': -6.254485}",False,False,30,1,29,OPEN,2024-04-09 11:00:11
113,88,dublin,BLACKHALL PLACE,Blackhall Place,"{'lat': 53.3488, 'lng': -6.281637}",False,False,30,20,10,OPEN,2024-04-09 11:02:19

In [11]:
df['latitude'] = df['position'].apply(lambda x: x['lat'])
df['longitude'] = df['position'].apply(lambda x: x['lng'])

In [12]:
df

,number,contract_name,name,address,position,banking,bonus,bike_stands,available_bike_stands,available_bikes,status,last_update,latitude,longitude
0,42,dublin,SMITHFIELD NORTH,Smithfield North,"{'lat': 53.349562, 'lng': -6.278198}",False,False,30,26,4,OPEN,2024-04-09 11:04:25,53.349562,-6.278198
1,30,dublin,PARNELL SQUARE NORTH,Parnell Square North,"{'lat': 53.3537415547453, 'lng': -6.2653014478...",False,False,20,13,6,OPEN,2024-04-09 11:04:17,53.353742,-6.265301
2,54,dublin,CLONMEL STREET,Clonmel Street,"{'lat': 53.336021, 'lng': -6.26298}",False,False,33,27,6,OPEN,2024-04-09 11:04:07,53.336021,-6.262980
3,108,dublin,AVONDALE ROAD,Avondale Road,"{'lat': 53.359405, 'lng': -6.276142}",False,False,35,25,10,OPEN,2024-04-09 11:02:23,53.359405,-6.276142
4,20,dublin,JAMES STREET EAST,James Street East,"{'lat': 53.336597, 'lng': -6.248109}",False,False,30,1,29,OPEN,2024-04-09 11:04:01,53.336597,-6.248109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,39,dublin,WILTON TERRACE,Wilton Terrace,"{'lat': 53.332383, 'lng': -6.252717}",False,False,20,20,0,OPEN,2024-04-09 11:03:49,53.332383,-6.252717
110,83,dublin,EMMET ROAD,Emmet Road,"{'lat': 53.340714, 'lng': -6.308191}",False,False,40,28,12,OPEN,2024-04-09 11:02:23,53.340714,-6.308191
111,92,dublin,HEUSTON BRIDGE (NORTH),Heuston Bridge (North),"{'lat': 53.347802, 'lng': -6.292432}",False,False,40,40,0,OPEN,2024-04-09 11:04:59,53.347802,-6.292432
112,21,dublin,LEINSTER STREET SOUTH,Leinster Street South,"{'lat': 53.34218, 'lng': -6.254485}",False,False,30,1,29,OPEN,2024-04-09 11:00:11,53.342180,-6.254485
113,88,dublin,BLACKHALL PLACE,Blackhall Place,"{'lat': 53.3488, 'lng': -6.281637}",False,False,30,20,10,OPEN,2024-04-09 11:02:19,53.348800,-6.281637

In [13]:
def reverse_geocode(lat, lng):
    url = f"https://nominatim.openstreetmap.org/reverse?lat={lat}&lon={lng}&format=json"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        return data.get('display_name')
    return None

In [14]:
#df['location_name'] = df.apply(lambda row: reverse_geocode(row['latitude'], row['longitude']), axis=1)

In [15]:
#df

In [16]:
import requests

def fetch_data(endpoint):
    print("Fetching data from the API...")
    response = requests.get(endpoint)
    if response.status_code == 200:
        print("Data fetched successfully.")
        return response.json()
    else:
        print(f"Error: Failed to fetch data. Status code: {response.status_code}")
        return None

In [17]:
def upload_to_azure_sql(data, connection_string, table_name):
    print("Uploading data to Azure SQL Server...")
    try:
        conn = odbc.connect(connection_string)
        cursor = conn.cursor()

        # Check if the table exists
        cursor.execute(f"SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = '{table_name}'")
        if not cursor.fetchone():
            # Create the table if it doesn't exist
            create_table_query = f"CREATE TABLE {table_name} ("
            create_table_query += ", ".join([f"{col} VARCHAR(MAX)" for col in data.columns])  # Assuming all columns are VARCHAR(MAX)
            create_table_query += ")"
            cursor.execute(create_table_query)
            print(f"Table '{table_name}' created successfully.")

        # Construct the SQL query with parameterized placeholders
        placeholders = ', '.join(['?' for _ in range(len(data.columns))])
        columns = ', '.join(data.columns)

        # Iterate over the rows in the DataFrame and execute the insert statement
        for _, row in data.iterrows():
            # Convert row values to the appropriate data types and then to a tuple
            values = tuple(row.astype(str))  # Convert all values to string
            cursor.execute(f"INSERT INTO {table_name} ({columns}) VALUES ({placeholders})", values)

        # Commit the transaction and close the cursor
        conn.commit()
        cursor.close()
        conn.close()
        
        print("Data uploaded successfully.")
    except Exception as e:
        print("Error occurred while uploading data:", e)

In [18]:
def fetch_and_upload_data(endpoint, connection_string, total_duration_minutes):
    end_time = time.time() + (total_duration_minutes * 60)
    while time.time() < end_time:
        data = fetch_data(endpoint)
        if data:
            df = pd.DataFrame(data)
            df['latitude'] = df['position'].apply(lambda x: x['lat'])
            df['longitude'] = df['position'].apply(lambda x: x['lng'])
            df['location_name'] = df.apply(lambda row: reverse_geocode(row['latitude'], row['longitude']), axis=1)
            df.drop('position', axis=1, inplace=True)
            upload_to_azure_sql(df, connection_string, "public_cycle_db_09_04_2024")
        print("Waiting for 20 minutes before fetching again...")
        time.sleep(1200)

In [ ]:
connection_string = connection_string = "Driver={ODBC Driver 18 for SQL Server};Server=tcp:cycles.database.windows.net,1433;Database=dub_cycle_db;Uid={20014083@mydbs.ie};Pwd={wD3PP^;O};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;Authentication=ActiveDirectoryPassword"
total_duration_minutes = 12 * 60  # Fetch data for 12 hours
fetch_and_upload_data(endpoint, connection_string, total_duration_minutes)

Fetching data from the API...
Data fetched successfully.
Uploading data to Azure SQL Server...
Table 'public_cycle_db_09_04_2024' created successfully.
Data uploaded successfully.
Waiting for 20 minutes before fetching again...

In [ ]:
import pyodbc
import pandas as pd

def read_from_azure_sql(connection_string, table_name):
    try:
        conn = odbc.connect(connection_string)
        cursor = conn.cursor()

        # Execute a select query to fetch data from the specified table
        cursor.execute(f"SELECT * FROM {table_name}")

        # Fetch all rows from the result set
        rows = cursor.fetchall()

        # Convert the fetched data into a pandas DataFrame
        df = pd.DataFrame(rows, columns=[column[0] for column in cursor.description])

        # Close the cursor and connection
        cursor.close()
        conn.close()

        return df
    except Exception as e:
        print("Error occurred while reading data:", e)


table_name = "public_cycle_db_09_04_2024"

ud = read_from_azure_sql(connection_string, table_name)
print(df)